package autocookie

import autocookie.buyable.{BuildingRequirements as _, *}
import autocookie.buyable.BuildingRequirements.BuildingRequirements
import autocookie.buyable.Building.*
import autocookie.buyable.upgrade.*

object Buyables {
  def createUpgrades: Map[String, Upgrade] =
    Seq(
      //region Legacy
      new LegacyUpgrade("Legacy"),
      new LegacyUpgrade("How to bake your dragon", "Legacy"),
      new LegacyUpgrade("Classic dairy selection", "Legacy"),
      new LegacyUpgrade("Basic wallpaper assortment", "Classic dairy selection"),
      new LegacyUpgrade("Fanciful dairy selection", "Classic dairy selection"),
      new LegacyUpgrade("Heralds", "Legacy"),

      new LegacyUpgrade("Season switcher", "Legacy"),

      new LegacyUpgrade("Twin Gates of Transcendence", "Legacy"),
      new LegacyUpgrade("Angels", "Twin Gates of Transcendence"),
      new LegacyUpgrade("Archangels", "Angels"),
      new LegacyUpgrade("Virtues", "Archangels"),
      new LegacyUpgrade("Dominions", "Virtues"),
      new LegacyUpgrade("Cherubim", "Dominions"),
      new LegacyUpgrade("Kitten angels", "Dominions"),
      new LegacyUpgrade("Seraphim", "Cherubim"),
      new LegacyUpgrade("God", "Seraphim"),
      new LegacyUpgrade("Belphegor", "Twin Gates of Transcendence"),
      new LegacyUpgrade("Mammon", "Belphegor"),
      new LegacyUpgrade("Abaddon", "Mammon"),
      new LegacyUpgrade("Satan", "Abaddon"),
      new LegacyUpgrade("Asmodeus", "Satan"),
      new LegacyUpgrade("Beelzebub", "Asmodeus"),
      new LegacyUpgrade("Lucifer", "Beelzebub"),
      new LegacyUpgrade("Synergies Vol. I", "Dominions", "Satan"),
      new LegacyUpgrade("Synergies Vol. II", "Synergies Vol. I", "Seraphim", "Beelzebub"),
      new LegacyUpgrade("Chimera", "Synergies Vol. II", "God", "Lucifer"),

      new LegacyUpgrade("Persistent memory", "Legacy"),
      new LegacyUpgrade("Permanent upgrade slot I", "Legacy"),
      new LegacyUpgrade("Permanent upgrade slot II", "Permanent upgrade slot I"),
      new LegacyUpgrade("Permanent upgrade slot III", "Permanent upgrade slot II"),
      new LegacyUpgrade("Permanent upgrade slot IV", "Permanent upgrade slot III"),
      new LegacyUpgrade("Permanent upgrade slot V", "Permanent upgrade slot IV"),
      new LegacyUpgrade("Inspired checklist", "Persistent memory", "Permanent upgrade slot IV"),
      new LegacyUpgrade("Genius accounting", "Inspired checklist"),

      new LegacyUpgrade("Heavenly luck", "Legacy"),
      new LegacyUpgrade("Lasting fortune", "Heavenly luck"),
      new LegacyUpgrade("Decisive fate", "Lasting fortune"),
      new LegacyUpgrade("Golden switch", "Heavenly luck"),
      new LegacyUpgrade("Lucky digit", "Heavenly luck"),
      new LegacyUpgrade("Lucky number", "Lucky digit", "Lasting fortune"),
      new LegacyUpgrade("Lucky payout", "Lucky number", "Decisive fate"),
      new LegacyUpgrade("Residual luck", "Golden switch"),
      new LegacyUpgrade("Golden cookie alert sound", "Golden switch", "Decisive fate"),
      new LegacyUpgrade("Divine discount", "Decisive fate"),
      new LegacyUpgrade("Divine sales", "Decisive fate"),
      new LegacyUpgrade("Divine bakeries", "Divine discount", "Divine sales"),
      new LegacyUpgrade("Distilled essence of redoubled luck", "Divine bakeries", "Residual luck"),
      new LegacyUpgrade("Shimmering veil", "Distilled essence of redoubled luck"),
      new LegacyUpgrade("Cosmic beginner's luck", "Shimmering veil"),
      new LegacyUpgrade("Reinforced membrane", "Shimmering veil"),

      new LegacyUpgrade("Heavenly cookies", "Legacy"),
      new LegacyUpgrade("Tin of british tea biscuits", "Heavenly cookies"),
      new LegacyUpgrade("Box of macarons", "Heavenly cookies"),
      new LegacyUpgrade("Box of brand biscuits", "Heavenly cookies"),
      new LegacyUpgrade("Tin of butter cookies", "Heavenly cookies"),
      new LegacyUpgrade("Starter kit", "Tin of british tea biscuits", "Box of macarons", "Box of brand biscuits", "Tin of butter cookies"),
      new LegacyUpgrade("Starter kitchen", "Starter kit"),
      new LegacyUpgrade("Unholy bait", "Starter kitchen"),
      new LegacyUpgrade("Elder spice", "Unholy bait"),
      new LegacyUpgrade("Sacrilegious corruption", "Unholy bait"),
      new LegacyUpgrade("Wrinkly cookies", "Sacrilegious corruption", "Elder spice"),
      new LegacyUpgrade("Stevia Caelestis", "Wrinkly cookies"),
      new LegacyUpgrade("Sugar baking", "Stevia Caelestis"),
      new LegacyUpgrade("Sugar crystal cookies", "Sugar baking"),
      new LegacyUpgrade("Box of maybe cookies", "Sugar crystal cookies"),
      new LegacyUpgrade("Box of not cookies", "Sugar crystal cookies"),
      new LegacyUpgrade("Box of pastries", "Sugar crystal cookies"),
      //endregion,
      //region Cursor
      new BuildingUpgradeWithAchievement("Reinforced index finger", BuildingRequirements(Building.cursor -> 1), "Click"),
      new BuildingUpgradeWithAchievement("Carpal tunnel prevention cream", BuildingRequirements(Building.cursor -> 1), "Click"),
      new BuildingUpgrade("Ambidextrous", BuildingRequirements(Building.cursor -> 10)),
      new BuildingUpgrade("Thousand fingers", BuildingRequirements(Building.cursor -> 25)),
      new BuildingUpgradeWithAchievement("Million fingers", BuildingRequirements(Building.cursor -> 50), "Mouse wheel"),
      new BuildingUpgradeWithAchievement("Billion fingers", BuildingRequirements(Building.cursor -> 100), "Of Mice and Men"),
      new BuildingUpgrade("Trillion fingers", BuildingRequirements(Building.cursor -> 150)),
      new BuildingUpgradeWithAchievement("Quadrillion fingers", BuildingRequirements(Building.cursor -> 200), "The Digital"),
      new BuildingUpgrade("Quintillion fingers", BuildingRequirements(Building.cursor -> 250)),
      new BuildingUpgradeWithAchievement("Sextillion fingers", BuildingRequirements(Building.cursor -> 300), "Extreme polydactyly"),
      new BuildingUpgrade("Septillion fingers", BuildingRequirements(Building.cursor -> 350)),
      new BuildingUpgradeWithAchievement("Octillion fingers", BuildingRequirements(Building.cursor -> 400), "Dr. T"),
      new BuildingUpgrade("Nonillion fingers", BuildingRequirements(Building.cursor -> 450)),
      //endregion,
      //region Grandma
      new BuildingUpgradeWithAchievement("Forwards from grandma", BuildingRequirements(Building.grandma -> 1), "Grandma\'s cookies"),
      new BuildingUpgrade("Steel-plated rolling pins", BuildingRequirements(Building.grandma -> 5)),
      new BuildingUpgrade("Lubricated dentures", BuildingRequirements(Building.grandma -> 25)),
      new BuildingUpgradeWithAchievement("Prune juice", BuildingRequirements(Building.grandma -> 50), "Sloppy kisses"),
      new BuildingUpgradeWithAchievement("Double-thick glasses", BuildingRequirements(Building.grandma -> 100), "Retirement home"),
      new BuildingUpgradeWithAchievement("Aging agents", BuildingRequirements(Building.grandma -> 150), "Friend of the ancients"),
      new BuildingUpgradeWithAchievement("Xtreme walkers", BuildingRequirements(Building.grandma -> 200), "Ruler of the ancients"),
      new BuildingUpgradeWithAchievement("The Unbridling", BuildingRequirements(Building.grandma -> 250), "The old never bothered me anyway"),
      new BuildingUpgradeWithAchievement("Reverse dementia", BuildingRequirements(Building.grandma -> 300), "The agemaster"),
      new BuildingUpgradeWithAchievement("Timeproof hair dyes", BuildingRequirements(Building.grandma -> 350), "To oldly go"),
      new BuildingUpgradeWithAchievement("Good manners", BuildingRequirements(Building.grandma -> 400), "Aged well"),
      new BuildingUpgradeWithAchievement("Generation degeneration", BuildingRequirements(Building.grandma -> 450), "101st birthday"),
      new BuildingUpgradeWithAchievement("Visits", BuildingRequirements(Building.grandma -> 500), "Defense of the ancients"),

      new BuildingUpgrade("Farmer grandmas", BuildingRequirements(Building.grandma -> 1, Building.farm -> 15)),
      new BuildingUpgrade("Miner grandmas", BuildingRequirements(Building.grandma -> 1, Building.mine -> 15)),
      new BuildingUpgrade("Worker grandmas", BuildingRequirements(Building.grandma -> 1, Building.factory -> 15)),
      new BuildingUpgrade("Banker grandmas", BuildingRequirements(Building.grandma -> 1, Building.bank -> 15)),
      new BuildingUpgrade("Priestess grandmas", BuildingRequirements(Building.grandma -> 1, Building.temple -> 15)),
      new BuildingUpgrade("Witch grandmas", BuildingRequirements(Building.grandma -> 1, Building.wizardTower -> 15)),
      new BuildingUpgrade("Cosmic grandmas", BuildingRequirements(Building.grandma -> 1, Building.shipment -> 15)),
      new BuildingUpgrade("Transmuted grandmas", BuildingRequirements(Building.grandma -> 1, Building.alchemyLab -> 15)),
      new BuildingUpgrade("Altered grandmas", BuildingRequirements(Building.grandma -> 1, Building.portal -> 15)),
      new BuildingUpgrade("Grandmas\' grandmas", BuildingRequirements(Building.grandma -> 1, Building.timeMachine -> 15)),
      new BuildingUpgrade("Antigrandmas", BuildingRequirements(Building.grandma -> 1, Building.antimatterCondenser -> 15)),
      new BuildingUpgrade("Rainbow grandmas", BuildingRequirements(Building.grandma -> 1, Building.prism -> 15)),
      new BuildingUpgrade("Lucky grandmas", BuildingRequirements(Building.grandma -> 1, Building.chancemaker -> 15)),
      new BuildingUpgrade("Metagrandmas", BuildingRequirements(Building.grandma -> 1, Building.fractalEngine -> 15)),
      new BuildingUpgrade("Binary grandmas", BuildingRequirements(Building.grandma -> 1, Building.javascriptConsole -> 15)),
      new BuildingUpgrade("Alternate grandmas", BuildingRequirements(Building.grandma -> 1, Building.idleverse -> 15)),
      //endregion,
      //region Farm
      new BuildingUpgradeWithAchievement("Cheap hoes", BuildingRequirements(Building.farm -> 1), "Bought the farm"),
      new BuildingUpgrade("Fertilizer", BuildingRequirements(Building.farm -> 5)),
      new BuildingUpgrade("Cookie trees", BuildingRequirements(Building.farm -> 25)),
      new BuildingUpgradeWithAchievement("Genetically-modified cookies", BuildingRequirements(Building.farm -> 50), "Reap what you sow"),
      new BuildingUpgradeWithAchievement("Gingerbread scarecrows", BuildingRequirements(Building.farm -> 100), "Farm ill"),
      new BuildingUpgradeWithAchievement("Pulsar sprinklers", BuildingRequirements(Building.farm -> 150), "Perfected agriculture"),
      new BuildingUpgradeWithAchievement("Fudge fungus", BuildingRequirements(Building.farm -> 200), "Homegrown"),
      new BuildingUpgradeWithAchievement("Wheat triffids", BuildingRequirements(Building.farm -> 250), "Gardener extraordinaire"),
      new BuildingUpgradeWithAchievement("Humane pesticides", BuildingRequirements(Building.farm -> 300), "Seedy business"),
      new BuildingUpgradeWithAchievement("Barnstars", BuildingRequirements(Building.farm -> 350), "You and the beanstalk"),
      new BuildingUpgradeWithAchievement("Lindworms", BuildingRequirements(Building.farm -> 400), "Harvest moon"),
      new BuildingUpgradeWithAchievement("Global seed vault", BuildingRequirements(Building.farm -> 450), "Make like a tree"),
      new BuildingUpgradeWithAchievement("Reverse-veganism", BuildingRequirements(Building.farm -> 500), "Sharpest tool in the shed"),
      //endregion,
      //region Mine
      new BuildingUpgradeWithAchievement("Sugar gas", BuildingRequirements(Building.mine -> 1), "You know the drill"),
      new BuildingUpgrade("Megadrill", BuildingRequirements(Building.mine -> 5)),
      new BuildingUpgrade("Ultradrill", BuildingRequirements(Building.mine -> 25)),
      new BuildingUpgradeWithAchievement("Ultimadrill", BuildingRequirements(Building.mine -> 50), "Excavation site"),
      new BuildingUpgradeWithAchievement("H-bomb mining", BuildingRequirements(Building.mine -> 100), "Hollow the planet"),
      new BuildingUpgradeWithAchievement("Coreforge", BuildingRequirements(Building.mine -> 150), "Can you dig it"),
      new BuildingUpgradeWithAchievement("Planetsplitters", BuildingRequirements(Building.mine -> 200), "The center of the Earth"),
      new BuildingUpgradeWithAchievement("Canola oil wells", BuildingRequirements(Building.mine -> 250), "Tectonic ambassador"),
      new BuildingUpgradeWithAchievement("Mole people", BuildingRequirements(Building.mine -> 300), "Freak fracking"),
      new BuildingUpgradeWithAchievement("Mine canaries", BuildingRequirements(Building.mine -> 350), "Romancing the stone"),
      new BuildingUpgradeWithAchievement("Bore again", BuildingRequirements(Building.mine -> 400), "Mine?"),
      new BuildingUpgradeWithAchievement("Air mining", BuildingRequirements(Building.mine -> 450), "Cave story"),
      new BuildingUpgradeWithAchievement("Caramel alloys", BuildingRequirements(Building.mine -> 500), "Hey now, you're a rock"),
      //endregion,
      //region Factory
      new BuildingUpgradeWithAchievement("Sturdier conveyor belts", BuildingRequirements(Building.factory -> 1), "Production chain"),
      new BuildingUpgrade("Child labor", BuildingRequirements(Building.factory -> 5)),
      new BuildingUpgrade("Sweatshop", BuildingRequirements(Building.factory -> 25)),
      new BuildingUpgradeWithAchievement("Radium reactors", BuildingRequirements(Building.factory -> 50), "Industrial revolution"),
      new BuildingUpgradeWithAchievement("Recombobulators", BuildingRequirements(Building.factory -> 100), "Global warming"),
      new BuildingUpgradeWithAchievement("Deep-bake process", BuildingRequirements(Building.factory -> 150), "Ultimate automation"),
      new BuildingUpgradeWithAchievement("Cyborg workforce", BuildingRequirements(Building.factory -> 200), "Technocracy"),
      new BuildingUpgradeWithAchievement("78-hour days", BuildingRequirements(Building.factory -> 250), "Rise of the machines"),
      new BuildingUpgradeWithAchievement("Machine learning", BuildingRequirements(Building.factory -> 300), "Modern times"),
      new BuildingUpgradeWithAchievement("Brownie point system", BuildingRequirements(Building.factory -> 350), "Ex machina"),
      new BuildingUpgradeWithAchievement("\"Volunteer\" interns", BuildingRequirements(Building.factory -> 400), "In full gear"),
      new BuildingUpgradeWithAchievement("Behavioral reframing", BuildingRequirements(Building.factory -> 450), "In-cog-neato"),
      new BuildingUpgradeWithAchievement("The infinity engine", BuildingRequirements(Building.factory -> 500), "Break the mold"),
      //endregion,
      //region Bank
      new BuildingUpgradeWithAchievement("Taller tellers", BuildingRequirements(Building.bank -> 1), "Pretty penny"),
      new BuildingUpgrade("Scissor-resistant credit cards", BuildingRequirements(Building.bank -> 5)),
      new BuildingUpgrade("Acid-proof vaults", BuildingRequirements(Building.bank -> 25)),
      new BuildingUpgradeWithAchievement("Chocolate coins", BuildingRequirements(Building.bank -> 50), "Fit the bill"),
      new BuildingUpgradeWithAchievement("Exponential interest rates", BuildingRequirements(Building.bank -> 100), "A loan in the dark"),
      new BuildingUpgradeWithAchievement("Financial zen", BuildingRequirements(Building.bank -> 150), "Need for greed"),
      new BuildingUpgradeWithAchievement("Way of the wallet", BuildingRequirements(Building.bank -> 200), "It\'s the economy, stupid"),
      new BuildingUpgradeWithAchievement("The stuff rationale", BuildingRequirements(Building.bank -> 250), "Acquire currency"),
      new BuildingUpgradeWithAchievement("Edible money", BuildingRequirements(Building.bank -> 300), "The nerve of war"),
      new BuildingUpgradeWithAchievement("Grand supercycles", BuildingRequirements(Building.bank -> 350), "And I need it now"),
      new BuildingUpgradeWithAchievement("Rules of acquisition", BuildingRequirements(Building.bank -> 400), "Treacle tart economics"),
      new BuildingUpgradeWithAchievement("Altruistic loop", BuildingRequirements(Building.bank -> 450), "Save your breath because that's all you've got left"),
      new BuildingUpgradeWithAchievement("Diminishing tax returns", BuildingRequirements(Building.bank -> 500), "Get the show on, get paid"),
      //endregion,
      //region Temple
      new BuildingUpgradeWithAchievement("Golden idols", BuildingRequirements(Building.temple -> 1), "Your time to shrine"),
      new BuildingUpgrade("Sacrifices", BuildingRequirements(Building.temple -> 5)),
      new BuildingUpgrade("Delicious blessing", BuildingRequirements(Building.temple -> 25)),
      new BuildingUpgradeWithAchievement("Sun festival", BuildingRequirements(Building.temple -> 50), "New-age cult"),
      new BuildingUpgradeWithAchievement("Enlarged pantheon", BuildingRequirements(Building.temple -> 100), "New-age cult"),
      new BuildingUpgradeWithAchievement("Great Baker in the sky", BuildingRequirements(Building.temple -> 150), "Organized religion"),
      new BuildingUpgradeWithAchievement("Creation myth", BuildingRequirements(Building.temple -> 200), "Fanaticism"),
      new BuildingUpgradeWithAchievement("Theocracy", BuildingRequirements(Building.temple -> 250), "Zealotry"),
      new BuildingUpgradeWithAchievement("Sick rap prayers", BuildingRequirements(Building.temple -> 300), "Wololo"),
      new BuildingUpgradeWithAchievement("Psalm-reading", BuildingRequirements(Building.temple -> 350), "Pray on the weak"),
      new BuildingUpgradeWithAchievement("War of the gods", BuildingRequirements(Building.temple -> 400), "Holy cookies, grandma!"),
      new BuildingUpgradeWithAchievement("A novel idea", BuildingRequirements(Building.temple -> 450), "Vengeful and almighty"),
      new BuildingUpgradeWithAchievement("Apparitions", BuildingRequirements(Building.temple -> 500), "My world's on fire, how about yours"),
      //endregion,
      //region Wizard tower
      new BuildingUpgradeWithAchievement("Pointier hats", BuildingRequirements(Building.wizardTower -> 1), "Bewitched"),
      new BuildingUpgrade("Beardlier beards", BuildingRequirements(Building.wizardTower -> 5)),
      new BuildingUpgrade("Ancient grimoires", BuildingRequirements(Building.wizardTower -> 25)),
      new BuildingUpgradeWithAchievement("Kitchen curses", BuildingRequirements(Building.wizardTower -> 50), "The sorcerer\'s apprentice"),
      new BuildingUpgradeWithAchievement("School of sorcery", BuildingRequirements(Building.wizardTower -> 100), "Charms and enchantments"),
      new BuildingUpgradeWithAchievement("Dark formulas", BuildingRequirements(Building.wizardTower -> 150), "Curses and maledictions"),
      new BuildingUpgradeWithAchievement("Cookiemancy", BuildingRequirements(Building.wizardTower -> 200), "Magic kingdom"),
      new BuildingUpgradeWithAchievement("Rabbit trick", BuildingRequirements(Building.wizardTower -> 250), "The wizarding world"),
      new BuildingUpgradeWithAchievement("Deluxe tailored wands", BuildingRequirements(Building.wizardTower -> 300), "And now for my next trick, I'll need a volunteer from the audience"),
      new BuildingUpgradeWithAchievement("Immobile spellcasting", BuildingRequirements(Building.wizardTower -> 350), "It's a kind of magic"),
      new BuildingUpgradeWithAchievement("Electricity", BuildingRequirements(Building.wizardTower -> 400), "The Prestige"),
      new BuildingUpgradeWithAchievement("Spelling bees", BuildingRequirements(Building.wizardTower -> 450), "Spell it out for you"),
      new BuildingUpgradeWithAchievement("Wizard basements", BuildingRequirements(Building.wizardTower -> 500), "The meteor men beg to differ"),
      //endregion
      //region Shipment
      new BuildingUpgradeWithAchievement("Vanilla nebulae", BuildingRequirements(Building.shipment -> 1), "Expedition"),
      new BuildingUpgrade("Wormholes", BuildingRequirements(Building.shipment -> 5)),
      new BuildingUpgrade("Frequent flyer", BuildingRequirements(Building.shipment -> 25)),
      new BuildingUpgradeWithAchievement("Warp drive", BuildingRequirements(Building.shipment -> 50), "Galactic highway"),
      new BuildingUpgradeWithAchievement("Chocolate monoliths", BuildingRequirements(Building.shipment -> 100), "Far far away"),
      new BuildingUpgradeWithAchievement("Generation ship", BuildingRequirements(Building.shipment -> 150), "Type II civilization"),
      new BuildingUpgradeWithAchievement("Dyson sphere", BuildingRequirements(Building.shipment -> 200), "We come in peace"),
      new BuildingUpgradeWithAchievement("The final frontier", BuildingRequirements(Building.shipment -> 250), "Parsec-masher"),
      new BuildingUpgradeWithAchievement("Autopilot", BuildingRequirements(Building.shipment -> 300), "It's not delivery"),
      new BuildingUpgradeWithAchievement("Restaurants at the end of the universe", BuildingRequirements(Building.shipment -> 350), "Make it so"),
      new BuildingUpgradeWithAchievement("Universal alphabet", BuildingRequirements(Building.shipment -> 400), "That's just peanuts to space"),
      new BuildingUpgradeWithAchievement("Toroid universe", BuildingRequirements(Building.shipment -> 450), "Space space space space space"),
      new BuildingUpgradeWithAchievement("Prime directive", BuildingRequirements(Building.shipment -> 500), "Only shooting stars"),
      //endregion,
      //region Alchemy lab
      new BuildingUpgradeWithAchievement("Antimony", BuildingRequirements(Building.alchemyLab -> 1), "Transmutation"),
      new BuildingUpgrade("Essence of dough", BuildingRequirements(Building.alchemyLab -> 5)),
      new BuildingUpgrade("True chocolate", BuildingRequirements(Building.alchemyLab -> 25)),
      new BuildingUpgradeWithAchievement("Ambrosia", BuildingRequirements(Building.alchemyLab -> 50), "Transmogrification"),
      new BuildingUpgradeWithAchievement("Aqua crustulae", BuildingRequirements(Building.alchemyLab -> 100), "Gold member"),
      new BuildingUpgradeWithAchievement("Origin crucible", BuildingRequirements(Building.alchemyLab -> 150), "Gild wars"),
      new BuildingUpgradeWithAchievement("Theory of atomic fluidity", BuildingRequirements(Building.alchemyLab -> 200), "The secrets of the universe"),
      new BuildingUpgradeWithAchievement("Beige goo", BuildingRequirements(Building.alchemyLab -> 250), "The work of a lifetime"),
      new BuildingUpgradeWithAchievement("The advent of chemistry", BuildingRequirements(Building.alchemyLab -> 300), "Gold, Jerry! Gold!"),
      new BuildingUpgradeWithAchievement("On second thought", BuildingRequirements(Building.alchemyLab -> 350), "All that glitters is gold"),
      new BuildingUpgradeWithAchievement("Public betterment", BuildingRequirements(Building.alchemyLab -> 400), "Worth its weight in lead"),
      new BuildingUpgradeWithAchievement("Hermetic reconciliation", BuildingRequirements(Building.alchemyLab -> 450), "Don't get used to yourself, you're gonna have to change"),
      new BuildingUpgradeWithAchievement("Chromatic cycling", BuildingRequirements(Building.alchemyLab -> 500), "We could all use a little change"),
      //endregion
      //region Portal
      new BuildingUpgradeWithAchievement("Ancient tablet", BuildingRequirements(Building.portal -> 1), "A whole new world"),
      new BuildingUpgrade("Insane oatling workers", BuildingRequirements(Building.portal -> 5)),
      new BuildingUpgrade("Soul bond", BuildingRequirements(Building.portal -> 25)),
      new BuildingUpgradeWithAchievement("Sanity dance", BuildingRequirements(Building.portal -> 50), "Now you\'re thinking"),
      new BuildingUpgradeWithAchievement("Brane transplant", BuildingRequirements(Building.portal -> 100), "Dimensional shift"),
      new BuildingUpgradeWithAchievement("Deity-sized portals", BuildingRequirements(Building.portal -> 150), "Brain-split"),
      new BuildingUpgradeWithAchievement("End of times back-up plan", BuildingRequirements(Building.portal -> 200), "Realm of the Mad God"),
      new BuildingUpgradeWithAchievement("Maddening chants", BuildingRequirements(Building.portal -> 250), "A place lost in time"),
      new BuildingUpgradeWithAchievement("The real world", BuildingRequirements(Building.portal -> 300), "Forbidden zone"),
      new BuildingUpgradeWithAchievement("Dimensional garbage gulper", BuildingRequirements(Building.portal -> 350), "H̸̷͓̳̳̯̟͕̟͍͍̣͡ḛ̢̦̰̺̮̝͖͖̘̪͉͘͡ ̠̦͕̤̪̝̥̰̠̫̖̣͙̬͘ͅC̨̦̺̩̲̥͉̭͚̜̻̝̣̼͙̮̯̪o̴̡͇̘͎̞̲͇̦̲͞͡m̸̩̺̝̣̹̱͚̬̥̫̳̼̞̘̯͘ͅẹ͇̺̜́̕͢s̶̙̟̱̥̮̯̰̦͓͇͖͖̝͘͘͞"),
      new BuildingUpgradeWithAchievement("Embedded microportals", BuildingRequirements(Building.portal -> 400), "What happens in the vortex stays in the vortex"),
      new BuildingUpgradeWithAchievement("His advent", BuildingRequirements(Building.portal -> 450), "Objects in the mirror dimension are closer than they appear"),
      new BuildingUpgradeWithAchievement("Domestic rifts", BuildingRequirements(Building.portal -> 500), "Your brain gets smart but your head gets dumb"),
      //endregion,
      //region Time machine
      new BuildingUpgradeWithAchievement("Flux capacitors", BuildingRequirements(Building.timeMachine -> 1), "Time warp"),
      new BuildingUpgrade("Time paradox resolver", BuildingRequirements(Building.timeMachine -> 5)),
      new BuildingUpgrade("Quantum conundrum", BuildingRequirements(Building.timeMachine -> 25)),
      new BuildingUpgradeWithAchievement("Causality enforcer", BuildingRequirements(Building.timeMachine -> 50), "Alternate timeline"),
      new BuildingUpgradeWithAchievement("Yestermorrow comparators", BuildingRequirements(Building.timeMachine -> 100), "Rewriting history"),
      new BuildingUpgradeWithAchievement("Far future enactment", BuildingRequirements(Building.timeMachine -> 150), "Time duke"),
      new BuildingUpgradeWithAchievement("Great loop hypothesis", BuildingRequirements(Building.timeMachine -> 200), "Forever and ever"),
      new BuildingUpgradeWithAchievement("Cookietopian moments of maybe", BuildingRequirements(Building.timeMachine -> 250), "Heat death"),
      new BuildingUpgradeWithAchievement("Second seconds", BuildingRequirements(Building.timeMachine -> 300), "cookie clicker forever and forever a hundred years cookie clicker, all day long forever, forever a hundred times, over and over cookie clicker adventures dot com"),
      new BuildingUpgradeWithAchievement("Additional clock hands", BuildingRequirements(Building.timeMachine -> 350), "Way back then"),
      new BuildingUpgradeWithAchievement("Nostalgia", BuildingRequirements(Building.timeMachine -> 400), "Invited to yesterday's party"),
      new BuildingUpgradeWithAchievement("Split seconds", BuildingRequirements(Building.timeMachine -> 450), "Groundhog day"),
      new BuildingUpgradeWithAchievement("Patience abolished", BuildingRequirements(Building.timeMachine -> 500), "The years start coming"),
      //endregion
      //region Antimatter condensers
      new BuildingUpgradeWithAchievement("Sugar bosons", BuildingRequirements(Building.antimatterCondenser -> 1), "Antibatter"),
      new BuildingUpgrade("String theory", BuildingRequirements(Building.antimatterCondenser -> 5)),
      new BuildingUpgrade("Large macaron collider", BuildingRequirements(Building.antimatterCondenser -> 25)),
      new BuildingUpgradeWithAchievement("Big bang bake", BuildingRequirements(Building.antimatterCondenser -> 50), "Quirky quarks"),
      new BuildingUpgradeWithAchievement("Reverse cyclotrons", BuildingRequirements(Building.antimatterCondenser -> 100), "It does matter!"),
      new BuildingUpgradeWithAchievement("Nanocosmics", BuildingRequirements(Building.antimatterCondenser -> 150), "Molecular maestro"),
      new BuildingUpgradeWithAchievement("The Pulse", BuildingRequirements(Building.antimatterCondenser -> 200), "Walk the planck"),
      new BuildingUpgradeWithAchievement("Some other super-tiny fundamental particle? Probably?", BuildingRequirements(Building.antimatterCondenser -> 250), "Microcosm"),
      new BuildingUpgradeWithAchievement("Quantum comb", BuildingRequirements(Building.antimatterCondenser -> 300), "Scientists baffled everywhere"),
      new BuildingUpgradeWithAchievement("Baking Nobel prize", BuildingRequirements(Building.antimatterCondenser -> 350), "Exotic matter"),
      new BuildingUpgradeWithAchievement("The definite molecule", BuildingRequirements(Building.antimatterCondenser -> 400), "Downsizing"),
      new BuildingUpgradeWithAchievement("Flavor itself", BuildingRequirements(Building.antimatterCondenser -> 450), "A matter of perspective"),
      new BuildingUpgradeWithAchievement("Delicious pull", BuildingRequirements(Building.antimatterCondenser -> 500), "What a concept"),
      //endregion
      //region Prisms
      new BuildingUpgradeWithAchievement("Gem polish", BuildingRequirements(Building.prism -> 1), "Lone photon"),
      new BuildingUpgrade("9th color", BuildingRequirements(Building.prism -> 5)),
      new BuildingUpgrade("Chocolate light", BuildingRequirements(Building.prism -> 25)),
      new BuildingUpgradeWithAchievement("Grainbow", BuildingRequirements(Building.prism -> 50), "Dazzling glimmer"),
      new BuildingUpgradeWithAchievement("Pure cosmic light", BuildingRequirements(Building.prism -> 100), "Blinding flash"),
      new BuildingUpgradeWithAchievement("Glow-in-the-dark", BuildingRequirements(Building.prism -> 150), "Unending glow"),
      new BuildingUpgradeWithAchievement("Lux sanctorum", BuildingRequirements(Building.prism -> 200), "Rise and shine"),
      new BuildingUpgradeWithAchievement("Reverse shadows", BuildingRequirements(Building.prism -> 250), "Bright future"),
      new BuildingUpgradeWithAchievement("Crystal mirrors", BuildingRequirements(Building.prism -> 300), "Harmony of the spheres"),
      new BuildingUpgradeWithAchievement("Reverse theory of light", BuildingRequirements(Building.prism -> 350), "At the end of the tunnel"),
      new BuildingUpgradeWithAchievement("Light capture measures", BuildingRequirements(Building.prism -> 400), "My eyes"),
      new BuildingUpgradeWithAchievement("Light speed limit", BuildingRequirements(Building.prism -> 450), "Optical illusion"),
      new BuildingUpgradeWithAchievement("Occam's laser", BuildingRequirements(Building.prism -> 500), "You'll never shine if you don't glow"),
      //endregion,
      //region Chancemaker
      new BuildingUpgradeWithAchievement("Your lucky cookie", BuildingRequirements(Building.chancemaker -> 1), "Lucked out"),
      new BuildingUpgrade("\"All Bets Are Off\" magic coin", BuildingRequirements(Building.chancemaker -> 5)),
      new BuildingUpgrade("Winning lottery ticket", BuildingRequirements(Building.chancemaker -> 25)),
      new BuildingUpgradeWithAchievement("Four-leaf clover field", BuildingRequirements(Building.chancemaker -> 50), "What are the odds"),
      new BuildingUpgradeWithAchievement("A recipe book about books", BuildingRequirements(Building.chancemaker -> 100), "Grandma needs a new pair of shoes"),
      new BuildingUpgradeWithAchievement("Leprechaun village", BuildingRequirements(Building.chancemaker -> 150), "Million to one shot, doc"),
      new BuildingUpgradeWithAchievement("Improbability drive", BuildingRequirements(Building.chancemaker -> 200), "As luck would have it"),
      new BuildingUpgradeWithAchievement("Antisuperstistronics", BuildingRequirements(Building.chancemaker -> 250), "Ever in your favor"),
      new BuildingUpgradeWithAchievement("Bunnypedes", BuildingRequirements(Building.chancemaker -> 300), "Be a lady"),
      new BuildingUpgradeWithAchievement("Revised probabilistics", BuildingRequirements(Building.chancemaker -> 350), "Dicey business"),
      new BuildingUpgradeWithAchievement("0-sided dice", BuildingRequirements(Building.chancemaker -> 400), "Maybe a chance in hell, actually"),
      new BuildingUpgradeWithAchievement("A touch of determinism", BuildingRequirements(Building.chancemaker -> 450), "Jackpot"),
      new BuildingUpgradeWithAchievement("On a streak", BuildingRequirements(Building.chancemaker -> 500), "You'll never know if you don't go"),
      //endregion,
      //region Fractal Engine
      new BuildingUpgradeWithAchievement("Metabakeries", BuildingRequirements(Building.fractalEngine -> 1), "Self-contained"),
      new BuildingUpgrade("Mandelbrown sugar", BuildingRequirements(Building.fractalEngine -> 5)),
      new BuildingUpgrade("Fractoids", BuildingRequirements(Building.fractalEngine -> 25)),
      new BuildingUpgradeWithAchievement("Nested universe theory", BuildingRequirements(Building.fractalEngine -> 50), "Threw you for a loop"),
      new BuildingUpgradeWithAchievement("Menger sponge cake", BuildingRequirements(Building.fractalEngine -> 100), "The sum of its parts"),
      new BuildingUpgradeWithAchievement("One particularly good-humored cow", BuildingRequirements(Building.fractalEngine -> 150), "Bears repeating"),
      new BuildingUpgradeWithAchievement("Chocolate ouroboros", BuildingRequirements(Building.fractalEngine -> 200), "More of the same"),
      new BuildingUpgradeWithAchievement("Nested", BuildingRequirements(Building.fractalEngine -> 250), "Last recurse"),
      new BuildingUpgradeWithAchievement("Space-filling fibers", BuildingRequirements(Building.fractalEngine -> 300), "Out of one, many"),
      new BuildingUpgradeWithAchievement("Endless book of prose", BuildingRequirements(Building.fractalEngine -> 350), "An example of recursion"),
      new BuildingUpgradeWithAchievement("The set of all sets", BuildingRequirements(Building.fractalEngine -> 400), "For more information on this achievement, please refer to its title"),
      new BuildingUpgradeWithAchievement("This upgrade", BuildingRequirements(Building.fractalEngine -> 450), "I'm so meta, even this achievement"),
      new BuildingUpgradeWithAchievement("A box", BuildingRequirements(Building.fractalEngine -> 500), "Never get bored"),
      //endregion
      //region Javascript Console
      new BuildingUpgradeWithAchievement("The JavaScript console for dummies", BuildingRequirements(Building.javascriptConsole -> 1), "F12"),
      new BuildingUpgrade("64bit arrays", BuildingRequirements(Building.javascriptConsole -> 5)),
      new BuildingUpgrade("Stack overflow", BuildingRequirements(Building.javascriptConsole -> 25)),
      new BuildingUpgradeWithAchievement("Enterprise compiler", BuildingRequirements(Building.javascriptConsole -> 50), "Variable success"),
      new BuildingUpgradeWithAchievement("Syntactic sugar", BuildingRequirements(Building.javascriptConsole -> 100), "No comments"),
      new BuildingUpgradeWithAchievement("A nice cup of coffee", BuildingRequirements(Building.javascriptConsole -> 150), "Up to code"),
      new BuildingUpgradeWithAchievement("Just-in-time baking", BuildingRequirements(Building.javascriptConsole -> 200), "Works on my machine"),
      new BuildingUpgradeWithAchievement("cookies++", BuildingRequirements(Building.javascriptConsole -> 250), "Technical debt"),
      new BuildingUpgradeWithAchievement("Software updates", BuildingRequirements(Building.javascriptConsole -> 300), "Mind your language"),
      new BuildingUpgradeWithAchievement("Game.Loop", BuildingRequirements(Building.javascriptConsole -> 350), "Inconsolable"),
      new BuildingUpgradeWithAchievement("eval()", BuildingRequirements(Building.javascriptConsole -> 400), "Closure"),
      new BuildingUpgradeWithAchievement("Your biggest fans", BuildingRequirements(Building.javascriptConsole -> 450), "Dude what if we're all living in a simulation like what if we're all just code on a computer somewhere"),
      new BuildingUpgradeWithAchievement("Hacker shades", BuildingRequirements(Building.javascriptConsole -> 500), "Taking the back streets"),
      //endregion
      //region Idleverse
      new BuildingUpgradeWithAchievement("Manifest destiny", BuildingRequirements(Building.idleverse -> 1), "They'll never know what hit 'em"),
      new BuildingUpgrade("The multiverse in a nutshell", BuildingRequirements(Building.idleverse -> 5)),
      new BuildingUpgrade("All-conversion", BuildingRequirements(Building.idleverse -> 25)),
      new BuildingUpgradeWithAchievement("Multiverse agents", BuildingRequirements(Building.idleverse -> 50), "Well-versed"),
      new BuildingUpgradeWithAchievement("Escape plan", BuildingRequirements(Building.idleverse -> 100), "Ripe for the picking"),
      new BuildingUpgradeWithAchievement("Game design", BuildingRequirements(Building.idleverse -> 150), "Unreal"),
      new BuildingUpgradeWithAchievement("Sandbox universes", BuildingRequirements(Building.idleverse -> 200), "Once you've seen one"),
      new BuildingUpgradeWithAchievement("Multiverse wars", BuildingRequirements(Building.idleverse -> 250), "Spoils and plunder"),
      new BuildingUpgradeWithAchievement("Mobile ports", BuildingRequirements(Building.idleverse -> 300), "Nobody exists on purpose, nobody belongs anywhere"),
      new BuildingUpgradeWithAchievement("Encapsulated realities", BuildingRequirements(Building.idleverse -> 350), "Hyperspace expressway"),
      new BuildingUpgradeWithAchievement("Extrinsic clicking", BuildingRequirements(Building.idleverse -> 400), "Versatile"),
      new BuildingUpgradeWithAchievement("Universal idling", BuildingRequirements(Building.idleverse -> 450), "You are inevitable"),
      new BuildingUpgradeWithAchievement("Break the fifth wall", BuildingRequirements(Building.idleverse -> 500), "Away from this place"),
      //endregion
      //TODO: Heralds Upgrade,
      //region Heavenly Chips Power
      new HeavenlyChipUpgrade("Heavenly chip secret", 5),
      new HeavenlyChipUpgradeWithSingleUpgradeRequired("Heavenly cookie stand", 20, "Heavenly chip secret"),
      new HeavenlyChipUpgradeWithSingleUpgradeRequired("Heavenly bakery", 25, "Heavenly cookie stand"),
      new HeavenlyChipUpgradeWithSingleUpgradeRequired("Heavenly confectionery", 25, "Heavenly bakery"),
      new HeavenlyChipUpgradeWithSingleUpgradeRequired("Heavenly key", 25, "Heavenly confectionery"),
      //endregion
      //region Research/Bingo Center
      new ResearchUpgrade("Bingo center/Research facility"),
      new ResearchCookieUpgrade("Specialized chocolate chips", "Bingo center/Research facility", 1D),
      new ResearchCookieUpgrade("Designer cocoa beans", "Specialized chocolate chips", 2D),
      new ResearchUpgrade("Ritual rolling pins", "Designer cocoa beans"),
      new ResearchCookieUpgrade("Underworld ovens", "Ritual rolling pins", 3D),
      new ResearchUpgrade("One mind", "Underworld ovens"),
      new ResearchCookieUpgrade("Exotic nuts", "One mind", 4D),
      new ResearchUpgrade("Communal brainsweep", "Exotic nuts"),
      new ResearchCookieUpgrade("Arcane sugar", "Communal brainsweep", 5D),
      new ResearchUpgrade("Elder Pact", "Arcane sugar"),
      //endregion
      //region Kitten
      new KittenUpgrade("Kitten helpers", 0.52),
      new KittenUpgrade("Kitten workers", 1),
      new KittenUpgrade("Kitten engineers", 2),
      new KittenUpgrade("Kitten overseers", 3),
      new KittenUpgrade("Kitten managers", 4),
      new KittenUpgrade("Kitten accountants", 5),
      new KittenUpgrade("Kitten specialists", 6),
      new KittenUpgrade("Kitten experts", 7),
      new KittenUpgrade("Kitten consultants", 8),
      new KittenUpgrade("Kitten assistants to the regional manager", 9),
      new KittenUpgrade("Kitten marketeers", 10),
      new KittenUpgrade("Kitten analysts", 11),
      //endregion,
      //region Mouse
      new MouseUpgrade("Plastic mouse"),
      new MouseUpgrade("Iron mouse"),
      new MouseUpgrade("Titanium mouse"),
      new MouseUpgrade("Adamantium mouse"),
      new MouseUpgrade("Unobtainium mouse"),
      new MouseUpgrade("Eludium mouse"),
      new MouseUpgrade("Wishalloy mouse"),
      new MouseUpgrade("Fantasteel mouse"),
      new MouseUpgrade("Nevercrack mouse"),
      new MouseUpgrade("Armythril mouse"),
      new MouseUpgrade("Technobsidian mouse"),
      new MouseUpgrade("Plasmarble mouse"),
      new MouseUpgrade("Miraculite mouse"),
      //endregion,
      //region Golden Cookie
      new GoldenCookieUpgrade("Lucky day"),
      new GoldenCookieUpgrade("Serendipity"),
      new GoldenCookieUpgrade("Get lucky"),
      new GoldenCookieUpgrade("Golden goose egg"),
      new GoldenCookieUpgrade("Green yeast digestives"),
      //endregion
      //region Cookies
      new CookieUpgrade("Plain cookies"),
      new CookieUpgrade("Sugar cookies"),
      new CookieUpgrade("Oatmeal raisin cookies"),
      new CookieUpgrade("Peanut butter cookies"),
      new CookieUpgrade("Coconut cookies"),
      new CookieUpgrade("Almond cookies"),
      new CookieUpgrade("Hazelnut cookies"),
      new CookieUpgrade("Walnut cookies"),
      new CookieUpgrade("Cashew cookies"),
      new CookieUpgrade("White chocolate cookies"),
      new CookieUpgrade("Milk chocolate cookies"),
      new CookieUpgrade("Macadamia nut cookies"),
      new CookieUpgrade("Double-chip cookies"),
      new CookieUpgrade("White chocolate macadamia nut cookies"),
      new CookieUpgrade("All-chocolate cookies"),
      new CookieUpgrade("Dark chocolate-coated cookies"),
      new CookieUpgrade("White chocolate-coated cookies"),
      new CookieUpgrade("Eclipse cookies"),
      new CookieUpgrade("Zebra cookies"),
      new CookieUpgrade("Snickerdoodles"),
      new CookieUpgrade("Stroopwafels"),
      new CookieUpgrade("Macaroons"),
      new CookieUpgrade("Madeleines"),
      new CookieUpgrade("Palmiers"),
      new CookieUpgrade("Palets"),
      new CookieUpgrade("Sabl&eacute;s"),

      new CookieUpgradeWithSingleUpgradeRequired("Caramoas", "Box of brand biscuits"),
      new CookieUpgradeWithSingleUpgradeRequired("Sagalongs", "Box of brand biscuits"),
      new CookieUpgradeWithSingleUpgradeRequired("Shortfoils", "Box of brand biscuits"),
      new CookieUpgradeWithSingleUpgradeRequired("Win mints", "Box of brand biscuits"),
      new CookieUpgradeWithSingleUpgradeRequired("Fig gluttons", "Box of brand biscuits"),
      new CookieUpgradeWithSingleUpgradeRequired("Loreols", "Box of brand biscuits"),
      new CookieUpgradeWithSingleUpgradeRequired("Jaffa cakes", "Box of brand biscuits"),
      new CookieUpgradeWithSingleUpgradeRequired("Grease's cups", "Box of brand biscuits"),
      new CookieUpgradeWithSingleUpgradeRequired("Digits", "Box of brand biscuits"),
      new CookieUpgradeWithSingleUpgradeRequired("Lombardia cookies", "Box of brand biscuits"),
      new CookieUpgradeWithSingleUpgradeRequired("Bastenaken cookies", "Box of brand biscuits"),
      new CookieUpgradeWithSingleUpgradeRequired("Festivity loops", "Box of brand biscuits"),
      new CookieUpgradeWithSingleUpgradeRequired("Havabreaks", "Box of brand biscuits"),
      new CookieUpgradeWithSingleUpgradeRequired("Zilla wafers", "Box of brand biscuits"),
      new CookieUpgradeWithSingleUpgradeRequired("Dim Dams", "Box of brand biscuits"),
      new CookieUpgradeWithSingleUpgradeRequired("Pokey", "Box of brand biscuits"),

      new CookieUpgrade("Gingerbread men"),
      new CookieUpgrade("Gingerbread trees"),
      new CookieUpgrade("Pure black chocolate cookies"),
      new CookieUpgrade("Pure white chocolate cookies"),
      new CookieUpgrade("Ladyfingers"),
      new CookieUpgrade("Tuiles"),
      new CookieUpgrade("Chocolate-stuffed biscuits"),
      new CookieUpgrade("Checker cookies"),
      new CookieUpgrade("Butter cookies"),
      new CookieUpgrade("Cream cookies"),
      new CookieUpgrade("Gingersnaps"),
      new CookieUpgrade("Cinnamon cookies"),
      new CookieUpgrade("Vanity cookies"),
      new CookieUpgrade("Cigars"),
      new CookieUpgrade("Pinwheel cookies"),
      new CookieUpgrade("Fudge squares"),
      new CookieUpgrade("Shortbread biscuits"),
      new CookieUpgrade("Millionaires' shortbreads"),
      new CookieUpgrade("Caramel cookies"),
      new CookieUpgrade("Pecan sandies"),
      new CookieUpgrade("Moravian spice cookies"),
      new CookieUpgrade("Anzac biscuits"),
      new CookieUpgrade("Buttercakes"),
      new CookieUpgrade("Ice cream sandwiches"),
      new CookieUpgrade("Birthday cookie"),
      new CookieUpgrade("Pink biscuits"),
      new CookieUpgrade("Whole-grain cookies"),
      new CookieUpgrade("Candy cookies"),
      new CookieUpgrade("Big chip cookies"),
      new CookieUpgrade("One chip cookies"),
      new CookieUpgrade("Sprinkles cookies"),
      new CookieUpgrade("Peanut butter blossoms"),
      new CookieUpgrade("No-bake cookies"),
      new CookieUpgrade("Florentines"),
      new CookieUpgrade("Chocolate crinkles"),
      new CookieUpgrade("Maple cookies"),
      new CookieUpgrade("Persian rice cookies"),
      new CookieUpgrade("Norwegian cookies"),
      new CookieUpgrade("Crispy rice cookies"),
      new CookieUpgrade("Ube cookies"),
      new CookieUpgrade("Butterscotch cookies"),
      new CookieUpgrade("Speculaas"),
      new CookieUpgrade("Chocolate oatmeal cookies"),
      new CookieUpgrade("Molasses cookies"),
      new CookieUpgrade("Biscotti"),
      new CookieUpgrade("Waffle cookies"),
      new CookieUpgrade("Custard creams"),
      new CookieUpgrade("Bourbon biscuits"),
      new CookieUpgrade("Mini-cookies"),
      new CookieUpgrade("Whoopie pies"),
      new CookieUpgrade("Caramel wafer biscuits"),
      new CookieUpgrade("Chocolate chip mocha cookies"),
      new CookieUpgrade("Earl Grey cookies"),
      new CookieUpgrade("Chai tea cookies"),
      new CookieUpgrade("Corn syrup cookies"),
      new CookieUpgrade("Icebox cookies"),
      new CookieUpgrade("Graham crackers"),
      new CookieUpgrade("Hardtack"),
      new CookieUpgrade("Cornflake cookies"),
      new CookieUpgrade("Tofu cookies"),
      new CookieUpgrade("Gluten-free cookies"),
      new CookieUpgrade("Russian bread cookies"),
      new CookieUpgrade("Lebkuchen"),
      new CookieUpgrade("Aachener Printen"),
      new CookieUpgrade("Canistrelli"),
      new CookieUpgrade("Nice biscuits"),
      new CookieUpgrade("French pure butter cookies"),
      new CookieUpgrade("Petit beurre"),
      new CookieUpgrade("Nanaimo bars"),
      new CookieUpgrade("Berger cookies"),
      new CookieUpgrade("Chinsuko"),
      new CookieUpgrade("Panda koala biscuits"),
      new CookieUpgrade("Putri salju"),
      new CookieUpgrade("Milk cookies"),
      new CookieUpgrade("Kruidnoten"),
      new CookieUpgrade("Marie biscuits"),
      new CookieUpgrade("Meringue cookies"),
      new CookieUpgrade("Yogurt cookies"),
      new CookieUpgrade("Thumbprint cookies"),
      new CookieUpgrade("Pizzelle"),
      new CookieUpgrade("Granola cookies"),
      new CookieUpgrade("Ricotta cookies"),
      new CookieUpgrade("Roze koeken"),
      new CookieUpgrade("Peanut butter cup cookies"),
      new CookieUpgrade("Sesame cookies"),
      new CookieUpgrade("Taiyaki"),
      new CookieUpgrade("Vanillekipferl"),
      new CookieUpgrade("Battenberg biscuits"),
      new CookieUpgrade("Rosette cookies"),
      new CookieUpgrade("Gangmakers"),
      new CookieUpgrade("Welsh cookies"),
      new CookieUpgrade("Raspberry cheesecake cookies"),
      new CookieUpgrade("Bokkenpootjes"),
      new CookieUpgrade("Fat rascals"),
      new CookieUpgrade("Ischler cookies"),
      new CookieUpgrade("Matcha cookies"),

      new CookieUpgrade("Empire biscuits"),
      new CookieUpgradeWithSingleUpgradeRequired("British tea biscuits", "Tin of british tea biscuits"),
      new CookieUpgradeWithSingleUpgradeRequired("Chocolate british tea biscuits", "British tea biscuits"),
      new CookieUpgradeWithSingleUpgradeRequired("Round british tea biscuits", "Chocolate british tea biscuits"),
      new CookieUpgradeWithSingleUpgradeRequired("Round chocolate british tea biscuits", "Round british tea biscuits"),
      new CookieUpgradeWithSingleUpgradeRequired("Round british tea biscuits with heart motif", "Round chocolate british tea biscuits"),
      new CookieUpgradeWithSingleUpgradeRequired("Round chocolate british tea biscuits with heart motif", "Round british tea biscuits with heart motif"),

      new CookieUpgradeWithSingleUpgradeRequired("Butter horseshoes", "Tin of butter cookies"),
      new CookieUpgradeWithSingleUpgradeRequired("Butter pucks", "Tin of butter cookies"),
      new CookieUpgradeWithSingleUpgradeRequired("Butter knots", "Tin of butter cookies"),
      new CookieUpgradeWithSingleUpgradeRequired("Butter slabs", "Tin of butter cookies"),
      new CookieUpgradeWithSingleUpgradeRequired("Butter swirls", "Tin of butter cookies"),

      new CookieUpgradeWithSingleUpgradeRequired("Rose macarons", "Box of macarons"),
      new CookieUpgradeWithSingleUpgradeRequired("Lemon macarons", "Box of macarons"),
      new CookieUpgradeWithSingleUpgradeRequired("Chocolate macarons", "Box of macarons"),
      new CookieUpgradeWithSingleUpgradeRequired("Pistachio macarons", "Box of macarons"),
      new CookieUpgradeWithSingleUpgradeRequired("Hazelnut macarons", "Box of macarons"),
      new CookieUpgradeWithSingleUpgradeRequired("Violet macarons", "Box of macarons"),
      new CookieUpgradeWithSingleUpgradeRequired("Caramel macarons", "Box of macarons"),
      new CookieUpgradeWithSingleUpgradeRequired("Licorice macarons", "Box of macarons"),
      new CookieUpgradeWithSingleUpgradeRequired("Earl Grey macarons", "Box of macarons"),

      new CookieUpgradeWithSingleUpgradeRequired("Cookie dough", "Box of maybe cookies"),
      new CookieUpgradeWithSingleUpgradeRequired("Burnt cookie", "Box of maybe cookies"),
      new CookieUpgradeWithSingleUpgradeRequired("A chocolate chip cookie but with the chips picked off for some reason", "Box of maybe cookies"),
      new CookieUpgradeWithSingleUpgradeRequired("Flavor text cookie", "Box of maybe cookies"),
      new CookieUpgradeWithSingleUpgradeRequired("High-definition cookie", "Box of maybe cookies"),
      new CookieUpgradeWithSingleUpgradeRequired("Crackers", "Box of maybe cookies"),

      new CookieUpgradeWithSingleUpgradeRequired("Toast", "Box of not cookies"),
      new CookieUpgradeWithSingleUpgradeRequired("Peanut butter & jelly", "Box of not cookies"),
      new CookieUpgradeWithSingleUpgradeRequired("Wookies", "Box of not cookies"),
      new CookieUpgradeWithSingleUpgradeRequired("Cheeseburger", "Box of not cookies"),
      new CookieUpgradeWithSingleUpgradeRequired("One lone chocolate chip", "Box of not cookies"),
      new CookieUpgradeWithSingleUpgradeRequired("Pizza", "Box of not cookies"),
      new CookieUpgradeWithSingleUpgradeRequired("Candy", "Box of not cookies"),

      new CookieUpgradeWithSingleUpgradeRequired("Profiteroles", "Box of pastries"),
      new CookieUpgradeWithSingleUpgradeRequired("Jelly donut", "Box of pastries"),
      new CookieUpgradeWithSingleUpgradeRequired("Glazed donut", "Box of pastries"),
      new CookieUpgradeWithSingleUpgradeRequired("Chocolate cake", "Box of pastries"),
      new CookieUpgradeWithSingleUpgradeRequired("Strawberry cake", "Box of pastries"),
      new CookieUpgradeWithSingleUpgradeRequired("Apple pie", "Box of pastries"),
      new CookieUpgradeWithSingleUpgradeRequired("Lemon meringue pie", "Box of pastries"),
      new CookieUpgradeWithSingleUpgradeRequired("Butter croissant", "Box of pastries"),

      new CookieUpgradeWithSingleUpgradeRequired("Cookie crumbs", "Legacy"),
      new CookieUpgradeWithSingleUpgradeRequired("Chocolate chip cookie", "Legacy"),

      new CookieUpgrade("Milk chocolate butter biscuit", BuildingRequirements.generateRequirementsForAllBuildings(100)),
      new CookieUpgrade("Dark chocolate butter biscuit", BuildingRequirements.generateRequirementsForAllBuildings(150)),
      new CookieUpgrade("White chocolate butter biscuit", BuildingRequirements.generateRequirementsForAllBuildings(200)),
      new CookieUpgrade("Ruby chocolate butter biscuit", BuildingRequirements.generateRequirementsForAllBuildings(250)),
      new CookieUpgrade("Lavender chocolate butter biscuit", BuildingRequirements.generateRequirementsForAllBuildings(300)),
      new CookieUpgrade("Synthetic chocolate green honey butter biscuit", BuildingRequirements.generateRequirementsForAllBuildings(350)),
      new CookieUpgrade("Royal raspberry chocolate butter biscuit", BuildingRequirements.generateRequirementsForAllBuildings(400)),
      new CookieUpgrade("Ultra-concentrated high-energy chocolate butter biscuit", BuildingRequirements.generateRequirementsForAllBuildings(450)),
      new CookieUpgrade("Pure pitch-black chocolate butter biscuit", BuildingRequirements.generateRequirementsForAllBuildings(500)),
      new CookieUpgrade("Cosmic chocolate butter biscuit", BuildingRequirements.generateRequirementsForAllBuildings(550)),
      new CookieUpgrade("Butter biscuit (with butter)", BuildingRequirements.generateRequirementsForAllBuildings(600)),
      //endregion,
      //region Synergies
      new BuildingUpgradeWithSingleUpgradeRequired("Extra physics funding", "Synergies Vol. I", BuildingRequirements(Building.bank -> 15, Building.antimatterCondenser -> 15)),
      new BuildingUpgradeWithSingleUpgradeRequired("Contracts from beyond", "Synergies Vol. I", BuildingRequirements(Building.bank -> 15, Building.prism -> 15)),
      new BuildingUpgradeWithSingleUpgradeRequired("Quantum electronics", "Synergies Vol. I", BuildingRequirements(Building.factory -> 15, Building.antimatterCondenser -> 15)),
      new BuildingUpgradeWithSingleUpgradeRequired("Infernal crops", "Synergies Vol. I", BuildingRequirements(Building.farm -> 15, Building.portal -> 15)),
      new BuildingUpgradeWithSingleUpgradeRequired("Future almanacs", "Synergies Vol. I", BuildingRequirements(Building.farm -> 15, Building.timeMachine -> 15)),
      new BuildingUpgradeWithSingleUpgradeRequired("Primordial ores", "Synergies Vol. I", BuildingRequirements(Building.mine -> 15, Building.alchemyLab -> 15)),
      new BuildingUpgradeWithSingleUpgradeRequired("Gemmed talismans", "Synergies Vol. I", BuildingRequirements(Building.mine -> 15, Building.chancemaker -> 15)),
      new BuildingUpgradeWithSingleUpgradeRequired("Fossil fuels", "Synergies Vol. I", BuildingRequirements(Building.mine -> 15, Building.shipment -> 15)),
      new BuildingUpgradeWithSingleUpgradeRequired("Seismic magic", "Synergies Vol. I", BuildingRequirements(Building.mine -> 15, Building.wizardTower -> 15)),
      new BuildingUpgradeWithSingleUpgradeRequired("Recursive mirrors", "Synergies Vol. I", BuildingRequirements(Building.prism -> 15, Building.fractalEngine -> 15)),
      new BuildingUpgradeWithSingleUpgradeRequired("Relativistic parsec-skipping", "Synergies Vol. I", BuildingRequirements(Building.shipment -> 15, Building.timeMachine -> 15)),
      new BuildingUpgradeWithSingleUpgradeRequired("Paganism", "Synergies Vol. I", BuildingRequirements(Building.temple -> 15, Building.portal -> 15)),
      new BuildingUpgradeWithSingleUpgradeRequired("Arcane knowledge", "Synergies Vol. I", BuildingRequirements(Building.wizardTower -> 15, Building.alchemyLab -> 15)),
      new BuildingUpgradeWithSingleUpgradeRequired("Light magic", "Synergies Vol. I", BuildingRequirements(Building.wizardTower -> 15, Building.prism -> 15)),
      new BuildingUpgradeWithSingleUpgradeRequired("Script grannies", "Synergies Vol. I", BuildingRequirements(Building.grandma -> 15, Building.javascriptConsole -> 15)),
      new BuildingUpgradeWithSingleUpgradeRequired("Perforated mille-feuille cosmos", "Synergies Vol. I", BuildingRequirements(Building.portal -> 15, Building.idleverse -> 15)),


      new BuildingUpgradeWithSingleUpgradeRequired("Chemical proficiency", "Synergies Vol. II", BuildingRequirements(Building.alchemyLab -> 75, Building.antimatterCondenser -> 75)),
      new BuildingUpgradeWithSingleUpgradeRequired("Charm quarks", "Synergies Vol. II", BuildingRequirements(Building.antimatterCondenser -> 75, Building.chancemaker -> 75)),
      new BuildingUpgradeWithSingleUpgradeRequired("Gold fund", "Synergies Vol. II", BuildingRequirements(Building.bank -> 75, Building.alchemyLab -> 75)),
      new BuildingUpgradeWithSingleUpgradeRequired("Printing presses", "Synergies Vol. II", BuildingRequirements(Building.bank -> 75, Building.factory -> 75)),
      new BuildingUpgradeWithSingleUpgradeRequired("Mice clicking mice", "Synergies Vol. II", BuildingRequirements(Building.cursor -> 75, Building.fractalEngine -> 75)),
      new BuildingUpgradeWithSingleUpgradeRequired("Shipyards", "Synergies Vol. II", BuildingRequirements(Building.factory -> 75, Building.shipment -> 75)),
      new BuildingUpgradeWithSingleUpgradeRequired("Temporal overclocking", "Synergies Vol. II", BuildingRequirements(Building.factory -> 75, Building.timeMachine -> 75)),
      new BuildingUpgradeWithSingleUpgradeRequired("Rain prayer", "Synergies Vol. II", BuildingRequirements(Building.farm -> 75, Building.temple -> 75)),
      new BuildingUpgradeWithSingleUpgradeRequired("Asteroid mining", "Synergies Vol. II", BuildingRequirements(Building.mine -> 75, Building.shipment -> 75)),
      new BuildingUpgradeWithSingleUpgradeRequired("Abysmal glimmer", "Synergies Vol. II", BuildingRequirements(Building.prism -> 75, Building.portal -> 75)),
      new BuildingUpgradeWithSingleUpgradeRequired("Primeval glow", "Synergies Vol. II", BuildingRequirements(Building.prism -> 75, Building.timeMachine -> 75)),
      new BuildingUpgradeWithSingleUpgradeRequired("God particle", "Synergies Vol. II", BuildingRequirements(Building.temple -> 75, Building.antimatterCondenser -> 75)),
      new BuildingUpgradeWithSingleUpgradeRequired("Mystical energies", "Synergies Vol. II", BuildingRequirements(Building.temple -> 75, Building.prism -> 75)),
      new BuildingUpgradeWithSingleUpgradeRequired("Magical botany", "Synergies Vol. II", BuildingRequirements(Building.wizardTower -> 75, Building.farm -> 75)),
      new BuildingUpgradeWithSingleUpgradeRequired("Tombola computing", "Synergies Vol. II", BuildingRequirements(Building.chancemaker -> 75, Building.javascriptConsole -> 75)),
      new BuildingUpgradeWithSingleUpgradeRequired("Infraverses and superverses", "Synergies Vol. II", BuildingRequirements(Building.fractalEngine -> 75, Building.idleverse -> 75)),
      //endregion
      //region Easter
      new EasterCookieUpgrade("Chicken egg"),
      new EasterCookieUpgrade("Duck egg"),
      new EasterCookieUpgrade("Turkey egg"),
      new EasterCookieUpgrade("Quail egg"),
      new EasterCookieUpgrade("Robin egg"),
      new EasterCookieUpgrade("Ostrich egg"),
      new EasterCookieUpgrade("Cassowary egg"),
      new EasterCookieUpgrade("Salmon roe"),
      new EasterCookieUpgrade("Frogspawn"),
      new EasterCookieUpgrade("Shark egg"),
      new EasterCookieUpgrade("Turtle egg"),
      new EasterCookieUpgrade("Ant larva"),
      //new EasterCookieUpgrade("Golden goose egg"),
      //new EasterCookieUpgrade("Faberge egg"),
      //new EasterCookieUpgrade("Wrinklerspawn"),
      //new EasterCookieUpgrade("Cookie egg"),
      //new EasterCookieUpgrade("Omelette"),
      //new EasterCookieUpgrade("Chocolate egg"),
      //new EasterCookieUpgrade("Century egg"),
      //new EasterCookieUpgrade("\"egg\""),
      //endregion
    ).map(upgrade => upgrade.name -> upgrade).toMap

  def createAchievements: Map[String, Achievement] =
    Seq(
      //region Cursor
      new Achievement("Click", BuildingRequirements(Building.cursor -> 1)),
      new Achievement("Double-click", BuildingRequirements(Building.cursor -> 2)),
      new Achievement("Mouse wheel", BuildingRequirements(Building.cursor -> 50)),
      new Achievement("Of Mice and Men", BuildingRequirements(Building.cursor -> 100)),
      new Achievement("The Digital", BuildingRequirements(Building.cursor -> 200)),
      new Achievement("Extreme polydactyly", BuildingRequirements(Building.cursor -> 300)),
      new Achievement("Dr. T", BuildingRequirements(Building.cursor -> 400)),
      new Achievement("Thumbs, phalanges, metacarpals", BuildingRequirements(Building.cursor -> 500)),
      new Achievement("With her finger and her thumb", BuildingRequirements(Building.cursor -> 600)),
      new Achievement("Gotta hand it to you", BuildingRequirements(Building.cursor -> 700)),
      new Achievement("The devil's workshop", BuildingRequirements(Building.cursor -> 800)),
      //endregion
      //region Grandma
      new Achievement("Grandma\'s cookies", BuildingRequirements(Building.grandma -> 1)),
      new Achievement("Sloppy kisses", BuildingRequirements(Building.grandma -> 50)),
      new Achievement("Retirement home", BuildingRequirements(Building.grandma -> 100)),
      new Achievement("Friend of the ancients", BuildingRequirements(Building.grandma -> 150)),
      new Achievement("Ruler of the ancients", BuildingRequirements(Building.grandma -> 200)),
      new Achievement("The old never bothered me anyway", BuildingRequirements(Building.grandma -> 250)),
      new Achievement("The agemaster", BuildingRequirements(Building.grandma -> 300)),
      new Achievement("To oldly go", BuildingRequirements(Building.grandma -> 350)),
      new Achievement("Aged well", BuildingRequirements(Building.grandma -> 400)),
      new Achievement("101st birthday", BuildingRequirements(Building.grandma -> 450)),
      new Achievement("Defense of the ancients", BuildingRequirements(Building.grandma -> 500)),
      new Achievement("But wait 'til you get older", BuildingRequirements(Building.grandma -> 550)),
      new Achievement("Okay boomer", BuildingRequirements(Building.grandma -> 600)),
      new Achievement("Elder"),
      //endregion
      //region Farm
      new Achievement("Bought the farm", BuildingRequirements(Building.farm -> 1)),
      new Achievement("Reap what you sow", BuildingRequirements(Building.farm -> 50)),
      new Achievement("Farm ill", BuildingRequirements(Building.farm -> 100)),
      new Achievement("Perfected agriculture", BuildingRequirements(Building.farm -> 150)),
      new Achievement("Homegrown", BuildingRequirements(Building.farm -> 200)),
      new Achievement("Gardener extraordinaire", BuildingRequirements(Building.farm -> 250)),
      new Achievement("Seedy business", BuildingRequirements(Building.farm -> 300)),
      new Achievement("You and the beanstalk", BuildingRequirements(Building.farm -> 350)),
      new Achievement("Harvest moon", BuildingRequirements(Building.farm -> 400)),
      new Achievement("Make like a tree", BuildingRequirements(Building.farm -> 450)),
      new Achievement("Sharpest tool in the shed", BuildingRequirements(Building.farm -> 500)),
      new Achievement("Overripe", BuildingRequirements(Building.farm -> 550)),
      new Achievement("In the green", BuildingRequirements(Building.farm -> 600)),
      //endregion
      //region Mine
      new Achievement("You know the drill", BuildingRequirements(Building.mine -> 1)),
      new Achievement("Excavation site", BuildingRequirements(Building.mine -> 50)),
      new Achievement("Hollow the planet", BuildingRequirements(Building.mine -> 100)),
      new Achievement("Can you dig it", BuildingRequirements(Building.mine -> 150)),
      new Achievement("The center of the Earth", BuildingRequirements(Building.mine -> 200)),
      new Achievement("Tectonic ambassador", BuildingRequirements(Building.mine -> 250)),
      new Achievement("Freak fracking", BuildingRequirements(Building.mine -> 300)),
      new Achievement("Romancing the stone", BuildingRequirements(Building.mine -> 350)),
      new Achievement("Mine?", BuildingRequirements(Building.mine -> 400)),
      new Achievement("Cave story", BuildingRequirements(Building.mine -> 450)),
      new Achievement("Hey now, you're a rock", BuildingRequirements(Building.mine -> 500)),
      new Achievement("Rock on", BuildingRequirements(Building.mine -> 550)),
      new Achievement("Mountain out of a molehill, but like in a good way", BuildingRequirements(Building.mine -> 600)),
      //endregion
      //region Factory
      new Achievement("Production chain", BuildingRequirements(Building.factory -> 1)),
      new Achievement("Industrial revolution", BuildingRequirements(Building.factory -> 50)),
      new Achievement("Global warming", BuildingRequirements(Building.factory -> 100)),
      new Achievement("Ultimate automation", BuildingRequirements(Building.factory -> 150)),
      new Achievement("Technocracy", BuildingRequirements(Building.factory -> 200)),
      new Achievement("Rise of the machines", BuildingRequirements(Building.factory -> 250)),
      new Achievement("Modern times", BuildingRequirements(Building.factory -> 300)),
      new Achievement("Ex machina", BuildingRequirements(Building.factory -> 350)),
      new Achievement("In full gear", BuildingRequirements(Building.factory -> 400)),
      new Achievement("In-cog-neato", BuildingRequirements(Building.factory -> 450)),
      new Achievement("Break the mold", BuildingRequirements(Building.factory -> 500)),
      new Achievement("Self-manmade man", BuildingRequirements(Building.factory -> 550)),
      new Achievement("The wheels of progress", BuildingRequirements(Building.factory -> 600)),
      //endregion
      //region Bank
      new Achievement("Pretty penny", BuildingRequirements(Building.bank -> 1)),
      new Achievement("Fit the bill", BuildingRequirements(Building.bank -> 50)),
      new Achievement("A loan in the dark", BuildingRequirements(Building.bank -> 100)),
      new Achievement("Need for greed", BuildingRequirements(Building.bank -> 150)),
      new Achievement("It's the economy, stupid", BuildingRequirements(Building.bank -> 200)),
      new Achievement("Acquire currency", BuildingRequirements(Building.bank -> 250)),
      new Achievement("The nerve of war", BuildingRequirements(Building.bank -> 300)),
      new Achievement("And I need it now", BuildingRequirements(Building.bank -> 350)),
      new Achievement("Treacle tart economics", BuildingRequirements(Building.bank -> 400)),
      new Achievement("Save your breath because that's all you've got left", BuildingRequirements(Building.bank -> 450)),
      new Achievement("Get the show on, get paid", BuildingRequirements(Building.bank -> 500)),
      new Achievement("Checks out", BuildingRequirements(Building.bank -> 550)),
      new Achievement("That's rich", BuildingRequirements(Building.bank -> 600)),
      //endregion
      //region Temple
      new Achievement("Your time to shrine", BuildingRequirements(Building.temple -> 1)),
      new Achievement("Shady sect", BuildingRequirements(Building.temple -> 50)),
      new Achievement("New-age cult", BuildingRequirements(Building.temple -> 100)),
      new Achievement("Organized religion", BuildingRequirements(Building.temple -> 150)),
      new Achievement("Fanaticism", BuildingRequirements(Building.temple -> 200)),
      new Achievement("Zealotry", BuildingRequirements(Building.temple -> 250)),
      new Achievement("Wololo", BuildingRequirements(Building.temple -> 300)),
      new Achievement("Pray on the weak", BuildingRequirements(Building.temple -> 350)),
      new Achievement("Holy cookies, grandma!", BuildingRequirements(Building.temple -> 400)),
      new Achievement("Vengeful and almighty", BuildingRequirements(Building.temple -> 450)),
      new Achievement("My world's on fire, how about yours", BuildingRequirements(Building.temple -> 500)),
      new Achievement("Living on a prayer", BuildingRequirements(Building.temple -> 550)),
      new Achievement("Preaches and cream", BuildingRequirements(Building.temple -> 600)),
      //endregion
      //region Wizard Tower
      new Achievement("Bewitched", BuildingRequirements(Building.wizardTower -> 1)),
      new Achievement("The sorcerer's apprentice", BuildingRequirements(Building.wizardTower -> 50)),
      new Achievement("Charms and enchantments", BuildingRequirements(Building.wizardTower -> 100)),
      new Achievement("Curses and maledictions", BuildingRequirements(Building.wizardTower -> 150)),
      new Achievement("Magic kingdom", BuildingRequirements(Building.wizardTower -> 200)),
      new Achievement("The wizarding world", BuildingRequirements(Building.wizardTower -> 250)),
      new Achievement("And now for my next trick, I'll need a volunteer from the audience", BuildingRequirements(Building.wizardTower -> 300)),
      new Achievement("It's a kind of magic", BuildingRequirements(Building.wizardTower -> 350)),
      new Achievement("The Prestige", BuildingRequirements(Building.wizardTower -> 400)),
      new Achievement("Spell it out for you", BuildingRequirements(Building.wizardTower -> 450)),
      new Achievement("The meteor men beg to differ", BuildingRequirements(Building.wizardTower -> 500)),
      new Achievement("Higitus figitus migitus mum", BuildingRequirements(Building.wizardTower -> 550)),
      new Achievement("Magic thinking", BuildingRequirements(Building.wizardTower -> 600)),
      //endregion
      //region Shipment
      new Achievement("Expedition", BuildingRequirements(Building.shipment -> 1)),
      new Achievement("Galactic highway", BuildingRequirements(Building.shipment -> 50)),
      new Achievement("Far far away", BuildingRequirements(Building.shipment -> 100)),
      new Achievement("Type II civilization", BuildingRequirements(Building.shipment -> 150)),
      new Achievement("We come in peace", BuildingRequirements(Building.shipment -> 200)),
      new Achievement("Parsec-masher", BuildingRequirements(Building.shipment -> 250)),
      new Achievement("It's not delivery", BuildingRequirements(Building.shipment -> 300)),
      new Achievement("Make it so", BuildingRequirements(Building.shipment -> 350)),
      new Achievement("That's just peanuts to space", BuildingRequirements(Building.shipment -> 400)),
      new Achievement("Space space space space space", BuildingRequirements(Building.shipment -> 450)),
      new Achievement("Only shooting stars", BuildingRequirements(Building.shipment -> 500)),
      new Achievement("The incredible journey", BuildingRequirements(Building.shipment -> 550)),
      new Achievement("Is there life on Mars?", BuildingRequirements(Building.shipment -> 600)),
      //endregion
      //region Alchemy
      new Achievement("Transmutation", BuildingRequirements(Building.alchemyLab -> 1)),
      new Achievement("Transmogrification", BuildingRequirements(Building.alchemyLab -> 50)),
      new Achievement("Gold member", BuildingRequirements(Building.alchemyLab -> 100)),
      new Achievement("Gild wars", BuildingRequirements(Building.alchemyLab -> 150)),
      new Achievement("The secrets of the universe", BuildingRequirements(Building.alchemyLab -> 200)),
      new Achievement("The work of a lifetime", BuildingRequirements(Building.alchemyLab -> 250)),
      new Achievement("Gold, Jerry! Gold!", BuildingRequirements(Building.alchemyLab -> 300)),
      new Achievement("All that glitters is gold", BuildingRequirements(Building.alchemyLab -> 350)),
      new Achievement("Worth its weight in lead", BuildingRequirements(Building.alchemyLab -> 400)),
      new Achievement("Don't get used to yourself, you're gonna have to change", BuildingRequirements(Building.alchemyLab -> 450)),
      new Achievement("We could all use a little change", BuildingRequirements(Building.alchemyLab -> 500)),
      new Achievement("Just a phase", BuildingRequirements(Building.alchemyLab -> 550)),
      new Achievement("Bad chemistry", BuildingRequirements(Building.alchemyLab -> 600)),
      //endregion
      //region Portals
      new Achievement("A whole new world", BuildingRequirements(Building.portal -> 1)),
      new Achievement("Now you\'re thinking", BuildingRequirements(Building.portal -> 50)),
      new Achievement("Dimensional shift", BuildingRequirements(Building.portal -> 100)),
      new Achievement("Brain-split", BuildingRequirements(Building.portal -> 150)),
      new Achievement("Realm of the Mad God", BuildingRequirements(Building.portal -> 200)),
      new Achievement("A place lost in time", BuildingRequirements(Building.portal -> 250)),
      new Achievement("Forbidden zone", BuildingRequirements(Building.portal -> 300)),
      new Achievement("H̸̷͓̳̳̯̟͕̟͍͍̣͡ḛ̢̦̰̺̮̝͖͖̘̪͉͘͡ ̠̦͕̤̪̝̥̰̠̫̖̣͙̬͘ͅC̨̦̺̩̲̥͉̭͚̜̻̝̣̼͙̮̯̪o̴̡͇̘͎̞̲͇̦̲͞͡m̸̩̺̝̣̹̱͚̬̥̫̳̼̞̘̯͘ͅẹ͇̺̜́̕͢s̶̙̟̱̥̮̯̰̦͓͇͖͖̝͘͘͞", BuildingRequirements(Building.portal -> 350)),
      new Achievement("What happens in the vortex stays in the vortex", BuildingRequirements(Building.portal -> 400)),
      new Achievement("Objects in the mirror dimension are closer than they appear", BuildingRequirements(Building.portal -> 450)),
      new Achievement("Your brain gets smart but your head gets dumb", BuildingRequirements(Building.portal -> 500)),
      new Achievement("Don't let me leave, Murph", BuildingRequirements(Building.portal -> 550)),
      new Achievement("Reduced to gibbering heaps", BuildingRequirements(Building.portal -> 600)),
      //endregion
      //region Time Machines
      new Achievement("Time warp", BuildingRequirements(Building.timeMachine -> 1)),
      new Achievement("Alternate timeline", BuildingRequirements(Building.timeMachine -> 50)),
      new Achievement("Rewriting history", BuildingRequirements(Building.timeMachine -> 100)),
      new Achievement("Time duke", BuildingRequirements(Building.timeMachine -> 150)),
      new Achievement("Forever and ever", BuildingRequirements(Building.timeMachine -> 200)),
      new Achievement("Heat death", BuildingRequirements(Building.timeMachine -> 250)),
      new Achievement("cookie clicker forever and forever a hundred years cookie clicker, all day long forever, forever a hundred times, over and over cookie clicker adventures dot com", BuildingRequirements(Building.timeMachine -> 300)),//Y u do dis? No capital letter at start and huge ass achiev name!
      new Achievement("Way back then", BuildingRequirements(Building.timeMachine -> 350)),
      new Achievement("Invited to yesterday's party", BuildingRequirements(Building.timeMachine -> 400)),
      new Achievement("Groundhog day", BuildingRequirements(Building.timeMachine -> 450)),
      new Achievement("The years start coming", BuildingRequirements(Building.timeMachine -> 500)),
      new Achievement("Caveman to cosmos", BuildingRequirements(Building.timeMachine -> 550)),
      new Achievement("Back already?", BuildingRequirements(Building.timeMachine -> 600)),
      //endregion
      //region Antimatter Condensers
      new Achievement("Antibatter", BuildingRequirements(Building.antimatterCondenser -> 1)),
      new Achievement("Quirky quarks", BuildingRequirements(Building.antimatterCondenser -> 50)),
      new Achievement("It does matter!", BuildingRequirements(Building.antimatterCondenser -> 100)),
      new Achievement("Molecular maestro", BuildingRequirements(Building.antimatterCondenser -> 150)),
      new Achievement("Walk the planck", BuildingRequirements(Building.antimatterCondenser -> 200)),
      new Achievement("Microcosm", BuildingRequirements(Building.antimatterCondenser -> 250)),
      new Achievement("Scientists baffled everywhere", BuildingRequirements(Building.antimatterCondenser -> 300)),
      new Achievement("Exotic matter", BuildingRequirements(Building.antimatterCondenser -> 350)),
      new Achievement("Downsizing", BuildingRequirements(Building.antimatterCondenser -> 400)),
      new Achievement("A matter of perspective", BuildingRequirements(Building.antimatterCondenser -> 450)),
      new Achievement("What a concept", BuildingRequirements(Building.antimatterCondenser -> 500)),
      new Achievement("Particular tastes", BuildingRequirements(Building.antimatterCondenser -> 550)),
      new Achievement("Nuclear throne", BuildingRequirements(Building.antimatterCondenser -> 600)),
      //endregion
      //region Prims
      new Achievement("Lone photon", BuildingRequirements(Building.prism -> 1)),
      new Achievement("Dazzling glimmer", BuildingRequirements(Building.prism -> 50)),
      new Achievement("Blinding flash", BuildingRequirements(Building.prism -> 100)),
      new Achievement("Unending glow", BuildingRequirements(Building.prism -> 150)),
      new Achievement("Rise and shine", BuildingRequirements(Building.prism -> 200)),
      new Achievement("Bright future", BuildingRequirements(Building.prism -> 250)),
      new Achievement("Harmony of the spheres", BuildingRequirements(Building.prism -> 300)),
      new Achievement("At the end of the tunnel", BuildingRequirements(Building.prism -> 350)),
      new Achievement("My eyes", BuildingRequirements(Building.prism -> 400)),
      new Achievement("Optical illusion", BuildingRequirements(Building.prism -> 450)),
      new Achievement("You'll never shine if you don't glow", BuildingRequirements(Building.prism -> 500)),
      new Achievement("A light snack", BuildingRequirements(Building.prism -> 550)),
      new Achievement("Making light of the situation", BuildingRequirements(Building.prism -> 600)),
      //endregion
      //region Chancemakers
      new Achievement("Lucked out", BuildingRequirements(Building.chancemaker -> 1)),
      new Achievement("What are the odds", BuildingRequirements(Building.chancemaker -> 50)),
      new Achievement("Grandma needs a new pair of shoes", BuildingRequirements(Building.chancemaker -> 100)),
      new Achievement("Million to one shot, doc", BuildingRequirements(Building.chancemaker -> 150)),
      new Achievement("As luck would have it", BuildingRequirements(Building.chancemaker -> 200)),
      new Achievement("Ever in your favor", BuildingRequirements(Building.chancemaker -> 250)),
      new Achievement("Be a lady", BuildingRequirements(Building.chancemaker -> 300)),
      new Achievement("Dicey business", BuildingRequirements(Building.chancemaker -> 350)),
      new Achievement("Maybe a chance in hell, actually", BuildingRequirements(Building.chancemaker -> 400)),
      new Achievement("Jackpot", BuildingRequirements(Building.chancemaker -> 450)),
      new Achievement("You'll never know if you don't go", BuildingRequirements(Building.chancemaker -> 500)),
      new Achievement("Tempting fate", BuildingRequirements(Building.chancemaker -> 550)),
      new Achievement("Flip a cookie. Chips, I win. Crust, you lose.", BuildingRequirements(Building.chancemaker -> 600)),
      //endregion
      //region Fractal Engines
      new Achievement("Self-contained", BuildingRequirements(Building.fractalEngine -> 1)),
      new Achievement("Threw you for a loop", BuildingRequirements(Building.fractalEngine -> 50)),
      new Achievement("The sum of its parts", BuildingRequirements(Building.fractalEngine -> 100)),
      new Achievement("Bears repeating", BuildingRequirements(Building.fractalEngine -> 150)),
      new Achievement("More of the same", BuildingRequirements(Building.fractalEngine -> 200)),
      new Achievement("Last recurse", BuildingRequirements(Building.fractalEngine -> 250)),
      new Achievement("Out of one, many", BuildingRequirements(Building.fractalEngine -> 300)),
      new Achievement("An example of recursion", BuildingRequirements(Building.fractalEngine -> 350)),
      new Achievement("For more information on this achievement, please refer to its title", BuildingRequirements(Building.fractalEngine -> 400)),
      new Achievement("I'm so meta, even this achievement", BuildingRequirements(Building.fractalEngine -> 450)),
      new Achievement("Never get bored", BuildingRequirements(Building.fractalEngine -> 500)),
      new Achievement("Tautological", BuildingRequirements(Building.fractalEngine -> 550)),
      new Achievement("In and of itself", BuildingRequirements(Building.fractalEngine -> 600)),
      //endregion
      //region Javascript Console
      new Achievement("F12", BuildingRequirements(Building.javascriptConsole -> 1)),
      new Achievement("Variable success", BuildingRequirements(Building.javascriptConsole -> 50)),
      new Achievement("No comments", BuildingRequirements(Building.javascriptConsole -> 100)),
      new Achievement("Up to code", BuildingRequirements(Building.javascriptConsole -> 150)),
      new Achievement("Works on my machine", BuildingRequirements(Building.javascriptConsole -> 200)),
      new Achievement("Technical debt", BuildingRequirements(Building.javascriptConsole -> 250)),
      new Achievement("Mind your language", BuildingRequirements(Building.javascriptConsole -> 300)),
      new Achievement("Inconsolable", BuildingRequirements(Building.javascriptConsole -> 350)),
      new Achievement("Closure", BuildingRequirements(Building.javascriptConsole -> 400)),
      new Achievement("Dude what if we're all living in a simulation like what if we're all just code on a computer somewhere", BuildingRequirements(Building.javascriptConsole -> 450)),
      new Achievement("Taking the back streets", BuildingRequirements(Building.javascriptConsole -> 500)),
      new Achievement("Curly braces", BuildingRequirements(Building.javascriptConsole -> 550)),
      new Achievement("Duck typing", BuildingRequirements(Building.javascriptConsole -> 600)),
      //endregion
      //region Idleverse
      new Achievement("They'll never know what hit 'em", BuildingRequirements(Building.idleverse -> 1)),
      new Achievement("Well-versed", BuildingRequirements(Building.idleverse -> 50)),
      new Achievement("Ripe for the picking", BuildingRequirements(Building.idleverse -> 100)),
      new Achievement("Unreal", BuildingRequirements(Building.idleverse -> 150)),
      new Achievement("Once you've seen one", BuildingRequirements(Building.idleverse -> 200)),
      new Achievement("Spoils and plunder", BuildingRequirements(Building.idleverse -> 250)),
      new Achievement("Nobody exists on purpose, nobody belongs anywhere", BuildingRequirements(Building.idleverse -> 300)),
      new Achievement("Hyperspace expressway", BuildingRequirements(Building.idleverse -> 350)),
      new Achievement("Versatile", BuildingRequirements(Building.idleverse -> 400)),
      new Achievement("You are inevitable", BuildingRequirements(Building.idleverse -> 450)),
      new Achievement("Away from this place", BuildingRequirements(Building.idleverse -> 500)),
      new Achievement("Everywhere at once", BuildingRequirements(Building.idleverse -> 550)),
      new Achievement("Reject reality, substitute your own", BuildingRequirements(Building.idleverse -> 600)),
      //endregion
      //region All buildings
      new Achievement("One with everything", BuildingRequirements.generateRequirementsForAllBuildings(1)),
      new Achievement("Centennial", BuildingRequirements.generateRequirementsForAllBuildings(100)),
      new Achievement("Centennial and a half", BuildingRequirements.generateRequirementsForAllBuildings(150)),
      new Achievement("Bicentennial", BuildingRequirements.generateRequirementsForAllBuildings(200)),
      new Achievement("Bicentennial and a half", BuildingRequirements.generateRequirementsForAllBuildings(250)),
      new Achievement("Tricentennial", BuildingRequirements.generateRequirementsForAllBuildings(300)),
      new Achievement("Tricentennial and a half", BuildingRequirements.generateRequirementsForAllBuildings(350)),
      new Achievement("Quadricentennial", BuildingRequirements.generateRequirementsForAllBuildings(400)),
      new Achievement("Quadricentennial and a half", BuildingRequirements.generateRequirementsForAllBuildings(450)),
      new Achievement("Quincentennial", BuildingRequirements.generateRequirementsForAllBuildings(500)),
      new Achievement("Base 10", BuildingRequirements(Building.all.map(building => building -> ((Building.all.length - building.gameBuyable.id.toInt) * 10)): _*)),
      new Achievement("Mathematician", BuildingRequirements(Building.all.map(building => building -> math.min(128, math.pow(2, Building.all.length - 1 - building.gameBuyable.id).toInt)): _*)),
      //endregion
    ).map(upgrade => upgrade.name -> upgrade).toMap
}
